# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# controller_manager:
#   ros__parameters:
#     update_rate: 100
#     use_sim_time: true
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#     panda_arm_controller:
#       type: position_controllers/JointTrajectoryController
#       joints:
#         - panda_joint1
#         - panda_joint2
#         - panda_joint3
#         - panda_joint4
#         - panda_joint5
#         - panda_joint6
#         - panda_joint7
#     panda_hand_controller:
#       type: position_controllers/GripperActionController
#       joints:
#         - panda_finger_joint1
#         - panda_finger_joint2